name: Horoscopo diario

on:
  schedule:
    - cron: '10 05 * * *'   # Todos los días 05:10 UTC (~07:10 en España)
  workflow_dispatch:        # Permite lanzarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparar fecha y carpetas
        id: prep
        run: |
          DATE=$(TZ="Europe/Madrid" date +'%Y-%m-%d')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          mkdir -p data/$DATE data/latest

      - name: Descargar horóscopos (Aztro)
        run: |
          SIGNS=(aries taurus gemini cancer leo virgo libra scorpio sagittarius capricorn aquarius pisces)
          DATE="${{ steps.prep.outputs.DATE }}"
          for s in "${SIGNS[@]}"; do
            curl -s -X POST "https://aztro.sameerkumar.website?sign=$s&day=today" \
              -H 'Content-Length: 0' \
              -o "data/$DATE/$s.json"
            cp "data/$DATE/$s.json" "data/latest/$s.json"
          done

      - name: Commit y push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          git commit -m "Auto-update ${{ steps.prep.outputs.DATE }}" || echo "Sin cambios"
          git push
