name: Horoscopo diario

on:
  workflow_dispatch:
  schedule:
    - cron: '10 05 * * *'   # 07:10 Madrid (05:10 UTC)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Preparar carpetas
        run: mkdir -p data/latest tmp

      - name: Descargar 12 signos con reintentos y sin pisar si falla
        shell: bash
        run: |
          set -e
          SIGNS=(aries taurus gemini cancer leo virgo libra scorpio sagittarius capricorn aquarius pisces)
          for s in "${SIGNS[@]}"; do
            echo "===> $s"
            ok=0
            for i in {1..4}; do
              curl -s -X POST "https://aztro.sameerkumar.website?sign=$s&day=today" \
                   -H 'Content-Length: 0' \
                   -o "tmp/$s.json" && \
              grep -q '"current_date"' "tmp/$s.json" && { ok=1; break; }
              echo "Reintento $i para $s"; sleep 3
            done
            if [ $ok -eq 1 ]; then
              mv "tmp/$s.json" "data/latest/$s.json"
            else
              echo "API falló para $s: conservo el último bueno (no sobreescribo)."
            fi
            sleep 1
          done

      - name: Commit y push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          git commit -m "Auto-update horoscopo $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Sin cambios"
          git push
