name: Horoscopo diario

on:
  workflow_dispatch:        # <- para que aparezca el botón "Run workflow"
  schedule:
    - cron: '10 05 * * *'   # 07:10 Madrid (05:10 UTC)

permissions:
  contents: write           # <- permite hacer git push con GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparar carpetas
        run: mkdir -p data/latest

      - name: Descargar los 12 signos
        shell: bash
        run: |
          SIGNS=(aries taurus gemini cancer leo virgo libra scorpio sagittarius capricorn aquarius pisces)
          for s in "${SIGNS[@]}"; do
            echo "===> ${s}"
            curl -s -X POST "https://aztro.sameerkumar.website?sign=$s&day=today" \
              -H 'Content-Length: 0' \
              -o "data/latest/$s.json"
            grep -q '"current_date"' "data/latest/$s.json" || echo '{"current_date":"","description":"Sin datos hoy","compatibility":"","mood":"","color":""}' > "data/latest/$s.json"
          done

      - name: Commit y push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          git commit -m "Auto-update horoscopo" || echo "Sin cambios"
          git push
