Files
Go to file
t
github
README.md
app.js
index.html
manifest.json
privacy.html
service-worker.js
styles.css
horoscopo-vintage
/github/
zaitrece
zaitrece
Update horoscopo.yml
2b9d785
 · 
1 minute ago
Name	Last commit message	Last commit date
..
.github/workflows
Update horoscopo.yml
1 minute ago
workflows
Create horoscopo.yml
20 minutes ago
